name: publish

on:  
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3       
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore            
    - name: Build
      run: dotnet publish -r win-x64 -o publish -p:PublishSingleFile=true --self-contained true
                
    - name: List files in folder
      run: |
        Get-ChildItem -Path ${{ github.workspace }}/publish
          
    - uses: actions/upload-artifact@v3
      with:
        name: MSFSVariableWatcher
        path: |
          ${{ github.workspace }}/publish/
